# NightVision Plugin Configuration

# Potion effect settings
effects:
  # If true, shows Night Vision particles around the player.
  show-particles: false
  # If true, shows the Night Vision icon in the player's HUD.
  show-icon: false
  # If true, prevents players from removing the Night Vision effect by drinking milk.
  prevent-milk-removal: true

# If true, the plugin will apply the gamma night vision effect to players automatically on join.
apply-on-join: false

messages:
  prefix: "<dark_blue>NightVision<r>| "
  night-vision-enabled: "<green>Gamma has been enabled."
  night-vision-disabled: "<red>Gamma has been disabled."
  player-only: "<red>This command can only be run by a player."