name: NightVision
version: "${version}"
main: io.github.Chamogelastos.nightvision.NightVision
api-version: '1.21'
authors: [ "Chamogelastos" ]
commands:
  gamma:
    aliases: [nv]
permissions:
  nightvision.use:
    default: op
