name: NightVision
version: "${version}"
main: io.github.Chamogelastos.nightvision.NightVision
api-version: '1.21'
authors: [ "Chamogelastos" ]
permissions:
  nightvision.use:
    default: true
  nightvision.reload:
    default: op